name: Deploy Flask App

on:
    workflow_run:
        workflows: ["Docker Build & Push"] # Name of the upstream workflow
        types: [completed]
        branches:
            - main
    
jobs:

    deploy:
        if: github.event.workflow_run.conclusion == 'success'
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.event.workflow_run.head_sha }}

        runs-on: self-hosted

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Compose (optional, usually pre-installed on ubuntu-latest runners)
              uses: docker/setup-compose-action@v2 

            - name: deploy with docker compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always
