name: Portfolio

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

permissions:
    pages: write      
    id-token: write   
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }} 

        steps:
            # get access to your Portfolio code via pre-built actions
            # clones or checks out the code where this workflow is written
            # STEP 1
            - name: Checkout Code 
              uses: actions/checkout@v4 

            # setup GitHub Pages
            # STEP 2
            - name: Setup GitHub Pages
              uses: actions/configure-pages@v4

            # static code artifacts
            # STEP 3
            - name: Upload static files
              uses: actions/upload-pages-artifact@v4
              with:
                path: "."
            
            # Make page Live
            # STEP 4
            - name: Deploy to Github pages
              id: deployment
              uses: actions/deploy-pages@v4
