name: Python lint
on:
  push:
    branches:  [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: code_check
        uses: action/checkout@v4
      - name: serup python 3.13 
        uses: action/setup-python@v5
      - name: install dependencie
        run: pip install -r requirements.txt
      - name: run linter
        run: flake8 app.py
