# Run pytest on the Flask app
name: Tests

on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run tests
              run: pytest test_app.py -v
